In [ ]:
 import tensorflow as tf
 print(tf.__version__)

2.5.0


In [ ]:
#create a tensor with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix(has more than one dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#create a tensor
#in output shape= (3,2,3) = (3 = total main box, 2 = boxes in main box, 3= elements in one box)
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
  ## notes fro this lecture
  scalar =  a single number
  vector = anumber with direction (e.g wind speed or direction)
  matrix = 2 dimensional array of numbers
  tensor =  n dimensional array of numbers(when can be any numbers,
                                           0-dimension tensor= scalar,
                                           1-dimension tensor= vector)

notes fro this lecture
scalar =  a single number

vector = a number with direction (e.g wind speed or direction)

matrix = 2 dimensional array of numbers

tensor =  n dimensional array of numbers(when can be any numbers,
                                           0-dimension tensor= scalar,
                                           1-dimension tensor= vector)

##create tensors with tf.variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
##compare these two tensor methods
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try to change one of the element from changeable tensor
#changeable_tensor[0] = 7 == not working
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## creating random tensors

In [ ]:
#create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

uniform distribution refers to a type of probability distribution in which all outcomes are equally likely.


Normal distribution, also known as the Gaussian distribution, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean. In graph form, normal distribution will appear as a bell curve.
In a normal distribution the mean is zero and the standard deviation is 1. It has zero skew and a kurtosis of 3

### shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect)

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled) #randomly shuffled tensor along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global seed
tf.random.shuffle(not_shuffled) # here if we add seed its operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

## other ways to make tensors

In [ ]:
#create tensor of all once
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create tensor of all once
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### you can also turn numpy arrays into tensors

the main difference between numpy arrays and tensors
 tensors can be run on gpu(much faster)

In [ ]:
##tip = capital for matrix and  tensor and non-capital for vector
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #create numpy array in 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
##directly we give array om constant fun
A = tf.constant(numpy_A, shape=(3,4,2)) #(box,raw,column)
B = tf.constant(numpy_A, shape=(4,6))
C = tf.constant(numpy_A)
A,B,C

(<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
A.ndim, B.ndim, C.ndim

(3, 2, 1)

##getting information from our tensors
*   shape
*   rank
*   axis or dimension
*   size










In [ ]:
#create a rank 4 tensors (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][2][3][4]
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)
#size =120 # 2*3*4*5

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# get various attributes of our tensor
print('datatype of every element', rank_4_tensor.dtype)
print('number of dimensions (rank)',rank_4_tensor.ndim)
print('shape of tensor:', rank_4_tensor.shape)
print('elements along the 0 axis',rank_4_tensor.shape[0])
print('elements along the last axis',rank_4_tensor.shape[-1])
print('Total number of elements in out tensor', tf.size(rank_4_tensor).numpy())
print('Total number of elements in out tensor', tf.size(rank_4_tensor))

datatype of every element <dtype: 'float32'>
number of dimensions (rank) 4
shape of tensor: (2, 3, 4, 5)
elements along the 0 axis 2
elements along the last axis 5
Total number of elements in out tensor 120
Total number of elements in out tensor tf.Tensor(120, shape=(), dtype=int32)


## indexing the tensors

In [ ]:
#get the first two elemnets from each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element each dimension from each index except for the final one
rank_4_tensor[:1, :1, : , :1]
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
## creat rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, rank_2_tensor

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
##get the last item of each of our rank 2 tensor
#rank_2_tensor[0][-1].numpy(), rank_2_tensor[1][-1].numpy(),
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
## add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis] #[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis
#tf.expand_dims(rank_2_tensor,axis=0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## manipulating tensors (tensor operation)

**basic operations**

In [ ]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10 #original tensor is unchanged
# tensor - 10
#tensor = tensor +10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#multiplication
tensor*10
#tensor/10
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## matrix multiplication
in ml matrix multiplication very common


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor # its not a proper matrix mul its element-wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#matrix multiplication with python operator @
tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#create tensor (3,2) tensor
x = tf.constant([[2,3],[4,5],[7,8]])

y = tf.constant([[21,13],[14,15],[17,18]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[21, 13],
        [14, 15],
        [17, 18]], dtype=int32)>)

In [ ]:
tf.matmul(x,y) #x@y

InvalidArgumentError: ignored

In [ ]:
#first matrix 3*2 second 3*2
#they are not matching so we have to reshape
x = tf.reshape(x,shape=(2,3))

In [ ]:
tf.matmul(x,y) #x@y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[152, 143],
       [339, 314]], dtype=int32)>

In [ ]:
# can do the transpose #transpose also can change shape
# transpose change the axis == column to raw and raw to column
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 7],
       [4, 8]], dtype=int32)>

**The dot product**

matrix multiplication is also referred to as the dot product

you can perform matrix multiplication using
* tf.matmul()
* tf.tensordot()
* @


In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[21, 13],
        [14, 15],
        [17, 18]], dtype=int32)>)

In [ ]:
#perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x),y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[217, 212],
       [269, 258]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 87,  77,  82],
       [159, 137, 146],
       [267, 227, 242]], dtype=int32)>

In [ ]:
# check the values of y , reshape y and transposed y
print(y)
print('reshape with (2,3)',tf.reshape(y,shape=(2,3)))
print('transpose', tf.transpose(y))

tf.Tensor(
[[21 13]
 [14 15]
 [17 18]], shape=(3, 2), dtype=int32)
reshape with (2,3) tf.Tensor(
[[21 13 14]
 [15 17 18]], shape=(2, 3), dtype=int32)
transpose tf.Tensor(
[[21 14 17]
 [13 15 18]], shape=(2, 3), dtype=int32)


## changing the datatype of a tensors

In [ ]:
# create the tensor with default datatype (float32)
B = tf.constant([1.7, 7.9])
B.dtype

tf.float32

In [ ]:
 # change float32 to float 16 (precision reduction)
B = tf.cast(B, dtype = tf.int32)
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# get the absolute values = take the negatives and convert into positive numbers
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

##Lets go through the following forms of aggregation
* get the minimum
* max
* mean
* sum

In [ ]:
import numpy as np
E = tf.constant(np.random.randint(0,100, size =50))

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(E)
tf.reduce_max(E)
tf.reduce_sum(E)
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [ ]:
# find the variance of our tensor
import tensorflow_probability as tfp

tfp.stats.variance(E)
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=709.2724>

In [ ]:
# find the std
tf.math.reduce_std(tf.cast(E,dtype= tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=26.632168>

## Find the positional minimum and maximum

In [ ]:
# create tensor for Find the positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum #same for min
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#check
assert F[tf.argmax(F)] == tf.reduce_max(F)

## squeezing a tensor (removing all single dimension)

In [ ]:
# create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape,

(TensorShape([1, 1, 1, 1, 50]),)

In [ ]:
G_sqeezed = tf.squeeze(G)
G_sqeezed, G_sqeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## Onehotencoding tensors

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4) #depth = col(categories)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for onehot encoding
tf.one_hot(some_list,depth=4,on_value='sahil', off_value='daniel')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'sahil', b'daniel', b'daniel', b'daniel'],
       [b'daniel', b'sahil', b'daniel', b'daniel'],
       [b'daniel', b'daniel', b'sahil', b'daniel'],
       [b'daniel', b'daniel', b'daniel', b'sahil']], dtype=object)>

## squaring, log, sqaure root

In [ ]:
H = tf.range(1,10)

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32)) #method require non-int

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## tensors and numpy

In [ ]:
# create tensor with numpy
J = tf.constant(np.array([3.,7.,20.]))

In [ ]:
# convert tensor to numpy array
np.array(J), type(np.array(J))
#another method
J.numpy()

array([ 3.,  7., 20.])